# This is a basic workflow to help you get started with Actions

name: Build release and publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - with:
          fetch-depth: 0
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v2
      - with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run build
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
